### ISSUE TITLE
Tatiana B wants to pay 10 USD to have this issue fixed

### ISSUE THREAD

**Issue by tbotskina** [nikitakoselev/TogetherWeOpenSource#12]
Could you update the project? 
 For more details visit [https://mintycode.io](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=b2ffcd97-4698-4cd5-a26a-9380e65d82c3&owner=nikitakoselev&name=TogetherWeOpenSource)

**Comment by nikitakoselev** [comment]
The project is not active at the moment.
I will update the project if anything changes.
